QLOADLISTUSUARIOSBYORGANIZACAOANDDATAAGENDAMENTO

SELECT
    DISTINCT U.*
FROM
    USUARIO U
    JOIN TIPOAGENDAMENTOUSUARIOS T
    ON T.PROFISSIONALID = U.ID JOIN ORGANIZACAO O
    ON O.ID = U.ORGANIZACAODEFAULTID
    LEFT JOIN CONFIGURADORAGENDAMENTOESPECIAL C
    ON C.PROFISSIONALID = U.ID
WHERE
    T.TIPOAGENDAMENTOID = :TIPOAGENDAMENTOID
    AND ( (:ORGANIZACAOID = C.ORGANIZACAOID
    AND :DATAAGENDAMENTO BETWEEN C.DATAINICIO
    AND C.DATAFIM)
    OR (:ORGANIZACAOID = U.ORGANIZACAODEFAULTID) )
    AND ( NOT EXISTS (
        SELECT
            1
        FROM
            CONFIGURADORAGENDAMENTOESPECIAL C2
        WHERE
            C2.PROFISSIONALID = U.ID
            AND :DATAAGENDAMENTO BETWEEN C2.DATAINICIO
            AND C2.DATAFIM
    )
    OR EXISTS (
        SELECT
            1
        FROM
            CONFIGURADORAGENDAMENTOESPECIAL C3
        WHERE
            C3.ORGANIZACAOID = :ORGANIZACAOID
            AND C3.PROFISSIONALID = U.ID
            AND :DATAAGENDAMENTO BETWEEN C3.DATAINICIO
            AND C3.DATAFIM
    ) )
    AND U.ID NOT IN (
        SELECT
            C5.USUARIOID
        FROM
            CONFIGURADORAUSENCIA C4
            LEFT JOIN CONFIGURADORAUSENCIAUSUARIO C5
            ON C5.CONFIGURADORAUSENCIAID = C4.ID
        WHERE
            COALESCE(C4.DATAINICIOAUSENCIA <= :DATAAGENDAMENTO,
            TRUE)
            AND COALESCE(C4.DATAFIMAUSENCIA >= :DATAAGENDAMENTO,
            TRUE)
    )
    AND U.ATIVO = TRUE QLOADUSUARIOBYORGANIZACAOANDPROFISSIONALANDTIPOAGENDAMENTO
    SELECT
        DISTINCT U.*
    FROM
        USUARIO U
        JOIN TIPOAGENDAMENTOUSUARIOS T
        ON T.PROFISSIONALID = U.ID JOIN ORGANIZACAO O
        ON O.ID = U.ORGANIZACAODEFAULTID
        LEFT JOIN CONFIGURADORAGENDAMENTOESPECIAL C
        ON C.PROFISSIONALID = U.ID
    WHERE
        U.ID = :PROFISSIONALID
        AND T.TIPOAGENDAMENTOID = :TIPOAGENDAMENTOID
        AND ( (:ORGANIZACAOID = C.ORGANIZACAOID
        AND :DATAAGENDAMENTO BETWEEN C.DATAINICIO
        AND C.DATAFIM)
        OR (:ORGANIZACAOID = U.ORGANIZACAODEFAULTID) )
        AND ( NOT EXISTS (
            SELECT
                1
            FROM
                CONFIGURADORAGENDAMENTOESPECIAL C2
            WHERE
                C2.PROFISSIONALID = U.ID
                AND :DATAAGENDAMENTO BETWEEN C2.DATAINICIO
                AND C2.DATAFIM
        )
        OR EXISTS (
            SELECT
                1
            FROM
                CONFIGURADORAGENDAMENTOESPECIAL C3
            WHERE
                C3.ORGANIZACAOID = :ORGANIZACAOID
                AND C3.PROFISSIONALID = U.ID
                AND :DATAAGENDAMENTO BETWEEN C3.DATAINICIO
                AND C3.DATAFIM
        ) )
        AND NOT EXISTS (
            SELECT
                1
            FROM
                CONFIGURADORAUSENCIA C4
                LEFT JOIN CONFIGURADORAUSENCIAUSUARIO C5
                ON C5.CONFIGURADORAUSENCIAID = C4.ID
            WHERE
                C5.USUARIOID IN (:USUARIOID)
                AND COALESCE(C4.DATAINICIOAUSENCIA <= :DATAAGENDAMENTO,
                TRUE)
                AND COALESCE(C4.DATAFIMAUSENCIA >= :DATAAGENDAMENTO,
                TRUE)
        )
        AND U.ATIVO = TRUE