version: "3.3"

services:
  db:
    container_name: tcc-db
    image: pescador95/tcc-agendamento:db
    volumes:
      - ./db/data:/var/lib/postgresql/data
    build:
      context: ./postgres
      dockerfile: Dockerfile
    env_file:
      - ./postgres.env
    ports:
      - "5433:5433"
    networks:
      - internal-network

networks:
  internal-network:
    driver: bridge
