-- public.genero definition

-- Drop table

-- DROP TABLE public.genero;

CREATE TABLE PUBLIC.GENERO (
    ID INT8 NOT NULL,
    GENERO VARCHAR(255) NULL,
    CONSTRAINT GENERO_PKEY PRIMARY KEY (ID)
);

-- public.statusagendamento definition

-- Drop table

-- DROP TABLE public.statusagendamento;

CREATE TABLE PUBLIC.STATUSAGENDAMENTO (
    ID INT8 NOT NULL,
    STATUS VARCHAR(255) NULL,
    CONSTRAINT STATUSAGENDAMENTO_PKEY PRIMARY KEY (ID)
);

-- public.tipoagendamento definition

-- Drop table

-- DROP TABLE public.tipoagendamento;

CREATE TABLE PUBLIC.TIPOAGENDAMENTO (
    ID INT8 NOT NULL,
    TIPOAGENDAMENTO VARCHAR(255) NULL,
    CONSTRAINT TIPOAGENDAMENTO_PKEY PRIMARY KEY (ID)
);

-- public.tipocontrato definition

-- Drop table

-- DROP TABLE public.tipocontrato;

CREATE TABLE PUBLIC.TIPOCONTRATO (
    ID INT8 NOT NULL,
    DESCRICAO VARCHAR(255) NULL,
    TIPOCONTRATO VARCHAR(255) NULL,
    CONSTRAINT TIPOCONTRATO_PKEY PRIMARY KEY (ID)
);

-- public.agendamento definition

-- Drop table

-- DROP TABLE public.agendamento;

CREATE TABLE PUBLIC.AGENDAMENTO (
    ID INT8 NOT NULL,
    ATIVO BOOL NULL,
    COMPREFERENCIA BOOL NULL,
    DATAACAO TIMESTAMP NULL,
    DATAAGENDAMENTO DATE NULL,
    HORARIOAGENDAMENTO TIME NULL,
    NOMEPESSOA VARCHAR(255) NULL,
    NOMEPROFISSIONAL VARCHAR(255) NULL,
    SYSTEMDATEDELETED TIMESTAMP NULL,
    AGENDAMENTOOLDID INT8 NULL,
    ORGANIZACAOID INT8 NULL,
    PESSOAID INT8 NULL,
    PROFISSIONALID INT8 NULL,
    STATUSAGENDAMENTOID INT8 NULL,
    TIPOAGENDAMENTOID INT8 NULL,
    USUARIOID INT8 NULL,
    CONSTRAINT AGENDAMENTO_PKEY PRIMARY KEY (ID)
);

CREATE INDEX IAGENDAMENTOAK1 ON PUBLIC.AGENDAMENTO USING BTREE (DATAAGENDAMENTO, HORARIOAGENDAMENTO, PESSOAID, PROFISSIONALID, ORGANIZACAOID, STATUSAGENDAMENTOID, ATIVO);

-- public.atendimento definition

-- Drop table

-- DROP TABLE public.atendimento;

CREATE TABLE PUBLIC.ATENDIMENTO (
    ID INT8 NOT NULL,
    ATIVIDADE VARCHAR(255) NULL,
    ATIVO BOOL NULL,
    AVALIACAO VARCHAR(255) NULL,
    DATAACAO TIMESTAMP NULL,
    DATAATENDIMENTO TIMESTAMP NULL,
    EVOLUCAOSINTOMAS VARCHAR(255) NULL,
    SYSTEMDATEDELETED TIMESTAMP NULL,
    HISTORICOPESSOAID INT8 NULL,
    USUARIOID INT8 NULL,
    CONSTRAINT ATENDIMENTO_PKEY PRIMARY KEY (ID)
);

CREATE INDEX IATENDIMENTOAK1 ON PUBLIC.ATENDIMENTO USING BTREE (DATAATENDIMENTO, HISTORICOPESSOAID, ATIVO);

-- public.configuradoragendamento definition

-- Drop table

-- DROP TABLE public.configuradoragendamento;

CREATE TABLE PUBLIC.CONFIGURADORAGENDAMENTO (
    ID INT8 NOT NULL,
    AGENDADOMINGOMANHA BOOL NULL,
    AGENDADOMINGONOITE BOOL NULL,
    AGENDADOMINGOTARDE BOOL NULL,
    AGENDAMANHA BOOL NULL,
    AGENDANOITE BOOL NULL,
    AGENDASABADOMANHA BOOL NULL,
    AGENDASABADONOITE BOOL NULL,
    AGENDASABADOTARDE BOOL NULL,
    AGENDATARDE BOOL NULL,
    ATENDEDOMINGO BOOL NULL,
    ATENDESABADO BOOL NULL,
    CONFIGURADORORGANIZACAO BOOL NULL,
    DATAACAO TIMESTAMP NULL,
    HORAMINUTOINTERVALO TIME NULL,
    HORAMINUTOTOLERANCIA TIME NULL,
    HORARIOFIMMANHA TIME NULL,
    HORARIOFIMNOITE TIME NULL,
    HORARIOFIMTARDE TIME NULL,
    HORARIOINICIOMANHA TIME NULL,
    HORARIOINICIONOITE TIME NULL,
    HORARIOINICIOTARDE TIME NULL,
    NOME VARCHAR(255) NULL,
    ORGANIZACAOID INT8 NULL,
    PROFISSIONALID INT8 NULL,
    USUARIOID INT8 NULL,
    CONSTRAINT CONFIGURADORAGENDAMENTO_PKEY PRIMARY KEY (ID)
);

-- public.configuradoragendamentoespecial definition

-- Drop table

-- DROP TABLE public.configuradoragendamentoespecial;

CREATE TABLE PUBLIC.CONFIGURADORAGENDAMENTOESPECIAL (
    ID INT8 NOT NULL,
    DATAACAO TIMESTAMP NULL,
    DATAFIM DATE NULL,
    DATAINICIO DATE NULL,
    NOME VARCHAR(255) NULL,
    ORGANIZACAOID INT8 NULL,
    PROFISSIONALID INT8 NULL,
    USUARIOID INT8 NULL,
    CONSTRAINT CONFIGURADORAGENDAMENTOESPECIAL_PKEY PRIMARY KEY (ID)
);

CREATE INDEX ICONFIGURADORAGENDAMENTOESPECIALAK1 ON PUBLIC.CONFIGURADORAGENDAMENTOESPECIAL USING BTREE (DATAINICIO, DATAFIM, PROFISSIONALID, ORGANIZACAOID);

-- public.configuradoragendamentoespecialusuario definition

-- Drop table

-- DROP TABLE public.configuradoragendamentoespecialusuario;

CREATE TABLE PUBLIC.CONFIGURADORAGENDAMENTOESPECIALUSUARIO (
    PROFISSIONALID INT8 NOT NULL,
    CONFIGURADORAGENDAMENTOESPECIALID INT8 NOT NULL
);

-- public.configuradorausencia definition

-- Drop table

-- DROP TABLE public.configuradorausencia;

CREATE TABLE PUBLIC.CONFIGURADORAUSENCIA (
    ID INT8 NOT NULL,
    DATAACAO TIMESTAMP NULL,
    DATAFIMAUSENCIA DATE NULL,
    DATAINICIOAUSENCIA DATE NULL,
    HORAFIMAUSENCIA TIME NULL,
    HORAINICIOAUSENCIA TIME NULL,
    NOMEAUSENCIA VARCHAR(255) NULL,
    OBSERVACAO VARCHAR(255) NULL,
    USUARIOID INT8 NULL,
    CONSTRAINT CONFIGURADORAUSENCIA_PKEY PRIMARY KEY (ID)
);

CREATE INDEX ICONFIGURADORAUSENCIAAK1 ON PUBLIC.CONFIGURADORAUSENCIA USING BTREE (DATAINICIOAUSENCIA, DATAFIMAUSENCIA);

-- public.configuradorausenciausuario definition

-- Drop table

-- DROP TABLE public.configuradorausenciausuario;

CREATE TABLE PUBLIC.CONFIGURADORAUSENCIAUSUARIO (
    CONFIGURADORAUSENCIAID INT8 NOT NULL,
    USUARIOID INT8 NOT NULL
);

-- public.configuradorespecialtipoagendamento definition

-- Drop table

-- DROP TABLE public.configuradorespecialtipoagendamento;

CREATE TABLE PUBLIC.CONFIGURADORESPECIALTIPOAGENDAMENTO (
    CONFIGAGENDAMENTOESPECIALID INT8 NOT NULL,
    TIPOAGENDAMENTOID INT8 NOT NULL
);

-- public.configuradorferiado definition

-- Drop table

-- DROP TABLE public.configuradorferiado;

CREATE TABLE PUBLIC.CONFIGURADORFERIADO (
    ID INT8 NOT NULL,
    DATAACAO TIMESTAMP NULL,
    DATAFERIADO DATE NULL,
    HORAFIMFERIADO TIME NULL,
    HORAINICIOFERIADO TIME NULL,
    NOMEFERIADO VARCHAR(255) NULL,
    OBSERVACAO VARCHAR(255) NULL,
    USUARIOID INT8 NULL,
    CONSTRAINT CONFIGURADORFERIADO_PKEY PRIMARY KEY (ID)
);

CREATE INDEX ICONFIGURADORFERIADOAK1 ON PUBLIC.CONFIGURADORFERIADO USING BTREE (DATAFERIADO, HORAINICIOFERIADO, HORAFIMFERIADO);

-- public.configuradorferiadoorganizacao definition

-- Drop table

-- DROP TABLE public.configuradorferiadoorganizacao;

CREATE TABLE PUBLIC.CONFIGURADORFERIADOORGANIZACAO (
    CONFIGURADORFERIADOID INT8 NOT NULL,
    ORGANIZACAOID INT8 NOT NULL
);

-- public.contrato definition

-- Drop table

-- DROP TABLE public.contrato;

CREATE TABLE PUBLIC.CONTRATO (
    ID INT8 NOT NULL,
    ATIVO BOOL NULL,
    CONSIDERACOES VARCHAR(255) NULL,
    DATAACAO TIMESTAMP NULL,
    DATACONTRATO DATE NULL,
    NUMEROMAXIMOSESSOES INT4 NULL,
    SYSTEMDATEDELETED TIMESTAMP NULL,
    ORGANIZACAOID INT8 NULL,
    RESPONSAVELID INT8 NULL,
    TIPOCONTRATOID INT8 NULL,
    USUARIO_ID INT8 NULL,
    USUARIOID INT8 NULL,
    CONSTRAINT CONTRATO_PKEY PRIMARY KEY (ID)
);

-- public.endereco definition

-- Drop table

-- DROP TABLE public.endereco;

CREATE TABLE PUBLIC.ENDERECO (
    ID INT8 NOT NULL,
    ATIVO BOOL NULL,
    CEP VARCHAR(255) NULL,
    CIDADE VARCHAR(255) NULL,
    COMPLEMENTO VARCHAR(255) NULL,
    DATAACAO TIMESTAMP NULL,
    ESTADO VARCHAR(255) NULL,
    LOGRADOURO VARCHAR(255) NULL,
    NUMERO INT8 NULL,
    SYSTEMDATEDELETED TIMESTAMP NULL,
    USUARIO_ID INT8 NULL,
    USUARIOID INT8 NULL,
    CONSTRAINT ENDERECO_PKEY PRIMARY KEY (ID)
);

-- public.historicopessoa definition

-- Drop table

-- DROP TABLE public.historicopessoa;

CREATE TABLE PUBLIC.HISTORICOPESSOA (
    ID INT8 NOT NULL,
    ATIVO BOOL NULL,
    COMORBIDADES VARCHAR(255) NULL,
    DATAACAO TIMESTAMP NULL,
    DIAGNOSTICOCLINICO VARCHAR(255) NULL,
    MEDICAMENTOS VARCHAR(255) NULL,
    NOMEPESSOA VARCHAR(255) NULL,
    OCUPACAO VARCHAR(255) NULL,
    QUEIXAPRINCIPAL VARCHAR(255) NULL,
    RESPONSAVELCONTATO VARCHAR(255) NULL,
    SYSTEMDATEDELETED TIMESTAMP NULL,
    PESSOAID INT8 NULL,
    USUARIOID INT8 NULL,
    CONSTRAINT HISTORICOPESSOA_PKEY PRIMARY KEY (ID)
);

CREATE INDEX IHISTORICOPESSOAAK1 ON PUBLIC.HISTORICOPESSOA USING BTREE (PESSOAID, ATIVO);

-- public.organizacao definition

-- Drop table

-- DROP TABLE public.organizacao;

CREATE TABLE PUBLIC.ORGANIZACAO (
    ID INT8 NOT NULL,
    ATIVO BOOL NULL,
    CELULAR VARCHAR(255) NULL,
    CNPJ VARCHAR(255) NULL,
    DATAACAO TIMESTAMP NULL,
    EMAIL VARCHAR(255) NULL,
    NOME VARCHAR(255) NULL,
    SYSTEMDATEDELETED TIMESTAMP NULL,
    TELEFONE VARCHAR(255) NULL,
    ENDERECOID INT8 NULL,
    HISTORICOPESSOA_ID INT8 NULL,
    TIPOAGENDAMENTO_ID INT8 NULL,
    USUARIO_ID INT8 NULL,
    USUARIOID INT8 NULL,
    CONSTRAINT ORGANIZACAO_PKEY PRIMARY KEY (ID)
);

-- public.perfilacesso definition

-- Drop table

-- DROP TABLE public.perfilacesso;

CREATE TABLE PUBLIC.PERFILACESSO (
    ID INT8 NOT NULL,
    APAGAR BOOL NULL,
    ATUALIZAR BOOL NULL,
    CRIAR BOOL NULL,
    DATAACAO TIMESTAMP NULL,
    LER BOOL NULL,
    NOME VARCHAR(255) NULL,
    USUARIOID INT8 NULL,
    CONSTRAINT PERFILACESSO_PKEY PRIMARY KEY (ID)
);

-- public.pessoa definition

-- Drop table

-- DROP TABLE public.pessoa;

CREATE TABLE PUBLIC.PESSOA (
    ID INT8 NOT NULL,
    ATIVO BOOL NULL,
    CELULAR VARCHAR(255) NULL,
    CPF VARCHAR(255) NULL,
    DATAACAO TIMESTAMP NULL,
    DATANASCIMENTO DATE NULL,
    EMAIL VARCHAR(255) NULL,
    NOME VARCHAR(255) NULL,
    SYSTEMDATEDELETED TIMESTAMP NULL,
    TELEFONE VARCHAR(255) NULL,
    ENDERECOID INT8 NULL,
    GENEROID INT8 NULL,
    USUARIOID INT8 NULL,
    CONSTRAINT PESSOA_PKEY PRIMARY KEY (ID)
);

CREATE INDEX IPESSOAAK1 ON PUBLIC.PESSOA USING BTREE (NOME, TELEFONE, CELULAR, DATANASCIMENTO, CPF, ATIVO);

-- public.profile definition

-- Drop table

-- DROP TABLE public.profile;

CREATE TABLE PUBLIC.PROFILE (
    ID INT8 NOT NULL,
    DATACRIADO TIMESTAMP NULL,
    FILEREFERENCE VARCHAR(255) NULL,
    FILESIZE INT8 NULL,
    KEYNAME VARCHAR(255) NULL,
    MIMETYPE VARCHAR(255) NULL,
    NOMECLIENTE VARCHAR(255) NULL,
    ORIGINALNAME VARCHAR(255) NULL,
    HISTORICOPESSOAID INT8 NULL,
    CONSTRAINT PROFILE_PKEY PRIMARY KEY (ID)
);

-- public."role" definition

-- Drop table

-- DROP TABLE public."role";

CREATE TABLE PUBLIC."role" (
    ID INT8 NOT NULL,
    "admin" BOOL NULL,
    PRIVILEGIO VARCHAR(255) NULL,
    USUARIO_ID INT8 NULL,
    CONSTRAINT ROLE_PKEY PRIMARY KEY (ID)
);

-- public.rotina definition

-- Drop table

-- DROP TABLE public.rotina;

CREATE TABLE PUBLIC.ROTINA (
    ID INT8 NOT NULL,
    DATAACAO TIMESTAMP NULL,
    ICON VARCHAR(255) NULL,
    NOME VARCHAR(255) NULL,
    "path" VARCHAR(255) NULL,
    TITULO VARCHAR(255) NULL,
    USUARIOID INT8 NULL,
    CONSTRAINT ROTINA_PKEY PRIMARY KEY (ID)
);

-- public.rotinaperfilacesso definition

-- Drop table

-- DROP TABLE public.rotinaperfilacesso;

CREATE TABLE PUBLIC.ROTINAPERFILACESSO (
    PERFILACESSOID INT8 NOT NULL,
    ROTINAID INT8 NOT NULL
);

-- public.tipoagendamentoorganizacoes definition

-- Drop table

-- DROP TABLE public.tipoagendamentoorganizacoes;

CREATE TABLE PUBLIC.TIPOAGENDAMENTOORGANIZACOES (
    TIPOAGENDAMENTOID INT8 NOT NULL,
    ORGANIZACAOID INT8 NOT NULL
);

-- public.tipoagendamentousuarios definition

-- Drop table

-- DROP TABLE public.tipoagendamentousuarios;

CREATE TABLE PUBLIC.TIPOAGENDAMENTOUSUARIOS (
    PROFISSIONALID INT8 NOT NULL,
    TIPOAGENDAMENTOID INT8 NOT NULL
);

-- public.usuario definition

-- Drop table

-- DROP TABLE public.usuario;

CREATE TABLE PUBLIC.USUARIO (
    ID INT8 NOT NULL,
    ALTERARSENHA BOOL NULL,
    ATIVO BOOL NULL,
    BOT BOOL NULL,
    DATAACAO TIMESTAMP NULL,
    LOGIN VARCHAR(255) NOT NULL,
    NOMEPROFISSIONAL VARCHAR(255) NULL,
    "password" VARCHAR(255) NOT NULL,
    SYSTEMDATEDELETED TIMESTAMP NULL,
    USUARIO VARCHAR(255) NULL,
    USUARIOACAO VARCHAR(255) NULL,
    ORGANIZACAODEFAULTID INT8 NULL,
    PESSOAID INT8 NULL,
    CONSTRAINT USUARIO_PKEY PRIMARY KEY (ID)
);

CREATE INDEX IUSUARIOAK1 ON PUBLIC.USUARIO USING BTREE (PESSOAID, LOGIN, ORGANIZACAODEFAULTID, ATIVO);

-- public.usuarioorganizacao definition

-- Drop table

-- DROP TABLE public.usuarioorganizacao;

CREATE TABLE PUBLIC.USUARIOORGANIZACAO (
    USUARIOID INT8 NOT NULL,
    ORGANIZACAOID INT8 NOT NULL
);

-- public.usuarioroles definition

-- Drop table

-- DROP TABLE public.usuarioroles;

CREATE TABLE PUBLIC.USUARIOROLES (
    USUARIOID INT8 NOT NULL,
    ROLEID INT8 NOT NULL
);

-- public.agendamento foreign keys

ALTER TABLE PUBLIC.AGENDAMENTO ADD CONSTRAINT FK2G04LBRUC4T7V13N6QYX5KJJ4 FOREIGN KEY (AGENDAMENTOOLDID) REFERENCES PUBLIC.AGENDAMENTO(ID);

ALTER TABLE PUBLIC.AGENDAMENTO ADD CONSTRAINT FK83P0TIC2BIOY7SM16EC5X8X11 FOREIGN KEY (PROFISSIONALID) REFERENCES PUBLIC.USUARIO(ID);

ALTER TABLE PUBLIC.AGENDAMENTO ADD CONSTRAINT FK8SDQM28UBLSMW1CXOOLWRE5YN FOREIGN KEY (USUARIOID) REFERENCES PUBLIC.USUARIO(ID);

ALTER TABLE PUBLIC.AGENDAMENTO ADD CONSTRAINT FKC1NASSQR26HHH9KXNPNKPAGV8 FOREIGN KEY (TIPOAGENDAMENTOID) REFERENCES PUBLIC.TIPOAGENDAMENTO(ID);

ALTER TABLE PUBLIC.AGENDAMENTO ADD CONSTRAINT FKE7YY6FC5QBX8BWN39YAW4IKYT FOREIGN KEY (ORGANIZACAOID) REFERENCES PUBLIC.ORGANIZACAO(ID);

ALTER TABLE PUBLIC.AGENDAMENTO ADD CONSTRAINT FKMG08HKNCJVMBQ6NEH35AAM5R8 FOREIGN KEY (STATUSAGENDAMENTOID) REFERENCES PUBLIC.STATUSAGENDAMENTO(ID);

ALTER TABLE PUBLIC.AGENDAMENTO ADD CONSTRAINT FKO2B5CXKLXBXETX1OJXACV1P6G FOREIGN KEY (PESSOAID) REFERENCES PUBLIC.PESSOA(ID);

-- public.atendimento foreign keys

ALTER TABLE PUBLIC.ATENDIMENTO ADD CONSTRAINT FKFOCGX3X82GP27DM0SIL7WRRHG FOREIGN KEY (HISTORICOPESSOAID) REFERENCES PUBLIC.HISTORICOPESSOA(ID);

ALTER TABLE PUBLIC.ATENDIMENTO ADD CONSTRAINT FKOYU7ENUII4GH6493CIQHE3KX FOREIGN KEY (USUARIOID) REFERENCES PUBLIC.USUARIO(ID);

-- public.configuradoragendamento foreign keys

ALTER TABLE PUBLIC.CONFIGURADORAGENDAMENTO ADD CONSTRAINT FKDKQS7218FYK8A9Y42G7903L9D FOREIGN KEY (ORGANIZACAOID) REFERENCES PUBLIC.ORGANIZACAO(ID);

ALTER TABLE PUBLIC.CONFIGURADORAGENDAMENTO ADD CONSTRAINT FKF5NLNM94DBBXLGBAHU524J2SC FOREIGN KEY (USUARIOID) REFERENCES PUBLIC.USUARIO(ID);

ALTER TABLE PUBLIC.CONFIGURADORAGENDAMENTO ADD CONSTRAINT FKI0GT8DT02IW81H3IKBQI90YET FOREIGN KEY (PROFISSIONALID) REFERENCES PUBLIC.USUARIO(ID);

-- public.configuradoragendamentoespecial foreign keys

ALTER TABLE PUBLIC.CONFIGURADORAGENDAMENTOESPECIAL ADD CONSTRAINT FK9CX249KIERSDL92V1N26TWG6Y FOREIGN KEY (ORGANIZACAOID) REFERENCES PUBLIC.ORGANIZACAO(ID);

ALTER TABLE PUBLIC.CONFIGURADORAGENDAMENTOESPECIAL ADD CONSTRAINT FK9MDV8QT4PFTK6ATXXM6STK5V9 FOREIGN KEY (USUARIOID) REFERENCES PUBLIC.USUARIO(ID);

ALTER TABLE PUBLIC.CONFIGURADORAGENDAMENTOESPECIAL ADD CONSTRAINT FKT40CP494N5AP8KXKPG4IHJKI1 FOREIGN KEY (PROFISSIONALID) REFERENCES PUBLIC.USUARIO(ID);

-- public.configuradoragendamentoespecialusuario foreign keys

ALTER TABLE PUBLIC.CONFIGURADORAGENDAMENTOESPECIALUSUARIO ADD CONSTRAINT FK327BHL0KN3JR3M82F5TQ93AU7 FOREIGN KEY (PROFISSIONALID) REFERENCES PUBLIC.USUARIO(ID);

ALTER TABLE PUBLIC.CONFIGURADORAGENDAMENTOESPECIALUSUARIO ADD CONSTRAINT FKET1K1WN4C073Q19OCFK6WE1RD FOREIGN KEY (CONFIGURADORAGENDAMENTOESPECIALID) REFERENCES PUBLIC.CONFIGURADORAGENDAMENTOESPECIAL(ID);

-- public.configuradorausencia foreign keys

ALTER TABLE PUBLIC.CONFIGURADORAUSENCIA ADD CONSTRAINT FK4F24EXNCJ1BLFI5R2BLR2CYF3 FOREIGN KEY (USUARIOID) REFERENCES PUBLIC.USUARIO(ID);

-- public.configuradorausenciausuario foreign keys

ALTER TABLE PUBLIC.CONFIGURADORAUSENCIAUSUARIO ADD CONSTRAINT FKHO4TOTLN732THP7RLE83LONFA FOREIGN KEY (USUARIOID) REFERENCES PUBLIC.USUARIO(ID);

ALTER TABLE PUBLIC.CONFIGURADORAUSENCIAUSUARIO ADD CONSTRAINT FKICVPH8O40ECV827AYYQ7O0YBT FOREIGN KEY (CONFIGURADORAUSENCIAID) REFERENCES PUBLIC.CONFIGURADORAUSENCIA(ID);

-- public.configuradorespecialtipoagendamento foreign keys

ALTER TABLE PUBLIC.CONFIGURADORESPECIALTIPOAGENDAMENTO ADD CONSTRAINT FK9PH6B7RIC1BAW3EVAHGB6OFH9 FOREIGN KEY (CONFIGAGENDAMENTOESPECIALID) REFERENCES PUBLIC.CONFIGURADORAGENDAMENTOESPECIAL(ID);

ALTER TABLE PUBLIC.CONFIGURADORESPECIALTIPOAGENDAMENTO ADD CONSTRAINT FKK8AFEC11Q5R2EXLJX71VY9JSH FOREIGN KEY (TIPOAGENDAMENTOID) REFERENCES PUBLIC.TIPOAGENDAMENTO(ID);

-- public.configuradorferiado foreign keys

ALTER TABLE PUBLIC.CONFIGURADORFERIADO ADD CONSTRAINT FK7F60TQA3CCT64W0VA4411WHDW FOREIGN KEY (USUARIOID) REFERENCES PUBLIC.USUARIO(ID);

-- public.configuradorferiadoorganizacao foreign keys

ALTER TABLE PUBLIC.CONFIGURADORFERIADOORGANIZACAO ADD CONSTRAINT FKKF0HF3AKR6SQXWHAQ8IHQGLO FOREIGN KEY (ORGANIZACAOID) REFERENCES PUBLIC.ORGANIZACAO(ID);

ALTER TABLE PUBLIC.CONFIGURADORFERIADOORGANIZACAO ADD CONSTRAINT FKSWYRX81T8VEIXN4TI7DTIHIXC FOREIGN KEY (CONFIGURADORFERIADOID) REFERENCES PUBLIC.CONFIGURADORFERIADO(ID);

-- public.contrato foreign keys

ALTER TABLE PUBLIC.CONTRATO ADD CONSTRAINT FK1VXRTSOAHFN7DPQ6I0O2SOOH4 FOREIGN KEY (RESPONSAVELID) REFERENCES PUBLIC.USUARIO(ID);

ALTER TABLE PUBLIC.CONTRATO ADD CONSTRAINT FK56MC6PC3KJOGEP3AXV0IXIHXG FOREIGN KEY (USUARIOID) REFERENCES PUBLIC.USUARIO(ID);

ALTER TABLE PUBLIC.CONTRATO ADD CONSTRAINT FK5DGS6AQYILHJ4OB3BS43FEYPX FOREIGN KEY (ORGANIZACAOID) REFERENCES PUBLIC.ORGANIZACAO(ID);

ALTER TABLE PUBLIC.CONTRATO ADD CONSTRAINT FKJK83WY5PQ0A7HUFODLIGIOP2K FOREIGN KEY (USUARIO_ID) REFERENCES PUBLIC.USUARIO(ID);

ALTER TABLE PUBLIC.CONTRATO ADD CONSTRAINT FKR9JAV3B0UFQXVPX7UOEBYTEDR FOREIGN KEY (TIPOCONTRATOID) REFERENCES PUBLIC.TIPOCONTRATO(ID);

-- public.endereco foreign keys

ALTER TABLE PUBLIC.ENDERECO ADD CONSTRAINT FK6692C20PHCMSX61PAYPL4VT9E FOREIGN KEY (USUARIOID) REFERENCES PUBLIC.USUARIO(ID);

ALTER TABLE PUBLIC.ENDERECO ADD CONSTRAINT FKEKDPB8K6GMP3LLLLA9D1QGMXK FOREIGN KEY (USUARIO_ID) REFERENCES PUBLIC.USUARIO(ID);

-- public.historicopessoa foreign keys

ALTER TABLE PUBLIC.HISTORICOPESSOA ADD CONSTRAINT FKIXVPKABC81PMPXDHHG52CN6QN FOREIGN KEY (USUARIOID) REFERENCES PUBLIC.USUARIO(ID);

ALTER TABLE PUBLIC.HISTORICOPESSOA ADD CONSTRAINT FKK5JMVO1EWMCAXEMJK200NHQ1J FOREIGN KEY (PESSOAID) REFERENCES PUBLIC.PESSOA(ID);

-- public.organizacao foreign keys

ALTER TABLE PUBLIC.ORGANIZACAO ADD CONSTRAINT FK79AO8FRUXWR9CWDLWGTF9724N FOREIGN KEY (ENDERECOID) REFERENCES PUBLIC.ENDERECO(ID);

ALTER TABLE PUBLIC.ORGANIZACAO ADD CONSTRAINT FK8SP6C91I3CRPL1UYTVK42AS1S FOREIGN KEY (HISTORICOPESSOA_ID) REFERENCES PUBLIC.HISTORICOPESSOA(ID);

ALTER TABLE PUBLIC.ORGANIZACAO ADD CONSTRAINT FKKJPPBR7SITU7SX52E2WGWAREG FOREIGN KEY (USUARIO_ID) REFERENCES PUBLIC.USUARIO(ID);

ALTER TABLE PUBLIC.ORGANIZACAO ADD CONSTRAINT FKRFGISC36GS2KEMYUWTIA69CUB FOREIGN KEY (TIPOAGENDAMENTO_ID) REFERENCES PUBLIC.TIPOAGENDAMENTO(ID);

ALTER TABLE PUBLIC.ORGANIZACAO ADD CONSTRAINT FKRQWCRQ8S5KO2LC72QRWEM3EMY FOREIGN KEY (USUARIOID) REFERENCES PUBLIC.USUARIO(ID);

-- public.perfilacesso foreign keys

ALTER TABLE PUBLIC.PERFILACESSO ADD CONSTRAINT FKKIVGAFIGHSLA43PCRU8BHC0YH FOREIGN KEY (USUARIOID) REFERENCES PUBLIC.USUARIO(ID);

-- public.pessoa foreign keys

ALTER TABLE PUBLIC.PESSOA ADD CONSTRAINT FKBIE98D5ETQCXSKB2XM8JKC61Q FOREIGN KEY (USUARIOID) REFERENCES PUBLIC.USUARIO(ID);

ALTER TABLE PUBLIC.PESSOA ADD CONSTRAINT FKCLO3UUJBGX4BGDUIQMDBMRS2N FOREIGN KEY (ENDERECOID) REFERENCES PUBLIC.ENDERECO(ID);

ALTER TABLE PUBLIC.PESSOA ADD CONSTRAINT FKGDMRBPLE6D3MI1XLD3F434RBD FOREIGN KEY (GENEROID) REFERENCES PUBLIC.GENERO(ID);

-- public.profile foreign keys

ALTER TABLE PUBLIC.PROFILE ADD CONSTRAINT FKKS6EKO1LMILKSTYUYVXTNH39M FOREIGN KEY (HISTORICOPESSOAID) REFERENCES PUBLIC.HISTORICOPESSOA(ID);

-- public."role" foreign keys

ALTER TABLE PUBLIC."role" ADD CONSTRAINT FKLHIUGV8UTQMJ6JPD5HWRF1JKR FOREIGN KEY (USUARIO_ID) REFERENCES PUBLIC.USUARIO(ID);

-- public.rotina foreign keys

ALTER TABLE PUBLIC.ROTINA ADD CONSTRAINT FK58HEYQ4LMSLL4DT4J77J4TAHO FOREIGN KEY (USUARIOID) REFERENCES PUBLIC.USUARIO(ID);

-- public.rotinaperfilacesso foreign keys

ALTER TABLE PUBLIC.ROTINAPERFILACESSO ADD CONSTRAINT FK38C297CJ9K63YSKAI25JOOJW8 FOREIGN KEY (PERFILACESSOID) REFERENCES PUBLIC.PERFILACESSO(ID);

ALTER TABLE PUBLIC.ROTINAPERFILACESSO ADD CONSTRAINT FKBIYFKT9VX0DEE410GIF51BH6X FOREIGN KEY (ROTINAID) REFERENCES PUBLIC.ROTINA(ID);

-- public.tipoagendamentoorganizacoes foreign keys

ALTER TABLE PUBLIC.TIPOAGENDAMENTOORGANIZACOES ADD CONSTRAINT FK4CAJRDAQPDUNVYT67FMNEIFVE FOREIGN KEY (TIPOAGENDAMENTOID) REFERENCES PUBLIC.TIPOAGENDAMENTO(ID);

ALTER TABLE PUBLIC.TIPOAGENDAMENTOORGANIZACOES ADD CONSTRAINT FKO256UFS0DX3TUWKF8AAMTGXIP FOREIGN KEY (ORGANIZACAOID) REFERENCES PUBLIC.ORGANIZACAO(ID);

-- public.tipoagendamentousuarios foreign keys

ALTER TABLE PUBLIC.TIPOAGENDAMENTOUSUARIOS ADD CONSTRAINT FK9VK62TFPK3EDRU3D4Y8MRC1KC FOREIGN KEY (PROFISSIONALID) REFERENCES PUBLIC.USUARIO(ID);

ALTER TABLE PUBLIC.TIPOAGENDAMENTOUSUARIOS ADD CONSTRAINT FKG3YJRMYYO4Q7A3RFSOII28DHQ FOREIGN KEY (TIPOAGENDAMENTOID) REFERENCES PUBLIC.TIPOAGENDAMENTO(ID);

-- public.usuario foreign keys

ALTER TABLE PUBLIC.USUARIO ADD CONSTRAINT FK290CEUW920X342VEW1XQYHQ4D FOREIGN KEY (PESSOAID) REFERENCES PUBLIC.PESSOA(ID);

ALTER TABLE PUBLIC.USUARIO ADD CONSTRAINT FK49WO0NEX16SHJ2JYN7J18SWEF FOREIGN KEY (ORGANIZACAODEFAULTID) REFERENCES PUBLIC.ORGANIZACAO(ID);

-- public.usuarioorganizacao foreign keys

ALTER TABLE PUBLIC.USUARIOORGANIZACAO ADD CONSTRAINT FKDFVTXSK957X0163Y7A4FCQDL3 FOREIGN KEY (ORGANIZACAOID) REFERENCES PUBLIC.ORGANIZACAO(ID);

ALTER TABLE PUBLIC.USUARIOORGANIZACAO ADD CONSTRAINT FKHF1DKVUH3A8PLAURAPS5T8LXU FOREIGN KEY (USUARIOID) REFERENCES PUBLIC.USUARIO(ID);

-- public.usuarioroles foreign keys

ALTER TABLE PUBLIC.USUARIOROLES ADD CONSTRAINT FKBB2234ORJJWLFY5XBUPV95YNS FOREIGN KEY (ROLEID) REFERENCES PUBLIC."role"(ID);

ALTER TABLE PUBLIC.USUARIOROLES ADD CONSTRAINT FKCJRJTWCOTTDMSE4WU618KFF27 FOREIGN KEY (USUARIOID) REFERENCES PUBLIC.USUARIO(ID);