version: "3.3"

services:
  redis:
    container_name: tcc-redis
    image: pescador95/tcc-agendamento:redis
    build:
      context: ./redis
      dockerfile: Dockerfile
    env_file:
      - ./redis.env
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    networks:
      - internal-network

networks:
  internal-network:
    driver: bridge
