QLOADLISTAGENDAMENTOSBYUSUARIODATAAGENDAORGANIZACAO

SELECT
    *
FROM
    AGENDAMENTO A
    JOIN ORGANIZACAO O
    ON A.ORGANIZACAOID = O.ID
    AND A.ATIVO = TRUE
    AND O.ATIVO = TRUE JOIN USUARIO U
    ON A.PROFISSIONALID = U.ID
    AND U.ATIVO = TRUE
WHERE
    O.ID = :ORGANIZACAOID
    AND U.ID = :PROFISSIONALID
    AND A.DATAAGENDAMENTO = :DATAAGENDAMENTO QLOADLISTAGENDAMENTOSBYDATAAGENDAORGANIZACAO
    SELECT
        *
    FROM
        AGENDAMENTO A
        JOIN ORGANIZACAO O
        ON A.ORGANIZACAOID = O.ID
        AND A.ATIVO = TRUE
        AND O.ATIVO = TRUE
    WHERE
        O.ID = :ORGANIZACAOID
        AND A.DATAAGENDAMENTO = :DATAAGENDAMENTO